### PR TITLE
fix dll install directory

### PR DESCRIPTION
**Pull request by tonytheodore**
`./configure` determines the correct `ddldir` for windows builds so use it in `Makefile.in`

### CODE REVIEW

**Comment by giraldeau** [comment]
Thanks for this patch, however the new CMake build system should install the libraries in the right place for Windows. Please test and report any issue. Thanks!

**Comment by tonytheodore** [comment]
This line in https://github.com/beltoforion/muparser/blob/master/CMakeLists.txt#L71:
```
install(TARGETS muparser DESTINATION lib)
```
should be something like:
```
install(TARGETS muparser
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION lib
    RUNTIME DESTINATION bin)
```
I'll try to test it sometime soon.

**Comment by tonytheodore** [comment]
See https://github.com/beltoforion/muparserx/blob/master/CMakeLists.txt#L68-L71

**Comment by giraldeau** [comment]
You are right, thanks thanks for the comment.

**Comment by giraldeau** [comment]
Actually, can we use ${CMAKE_INSTALL_LIBDIR} from GNUInstallDirs instead? I wonder if that would be more appropriate.

**Comment by tonytheodore** [comment]
I know much about GNUInstallDirs, but it does seem appropriate.

**Pull request closed without merging**
