### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jschueller**
- Fix DOS end of lines (git should handle that on the windows side)
- Remove latin1 chars (german...)
- Fix various warnings, only left the std::auto_ptr one!

### CODE REVIEW

**Comment by giraldeau** [comment]
That's great, it will take some time to review that amount of changes, even though it should be straightforward. Thanks!

**Comment by jschueller** [comment]
@giraldeau, is this ok for you? I would need these commits to go forward with fixing the win export stuff.

**Comment by jschueller** [comment]
@giraldeau I just rebased to your changes in master here so this can be merged

**Comment by jschueller** [comment]
ping @giraldeau

**Comment by beltoforion** [comment]
I merged it but is did not check it with windows yet. If there are problem with the line termination i may need to revert.

**Pull request merged**
