### PR TITLE
Allow for conditionally disabling tests

### PR DESCRIPTION
**Pull request by mliszcz**
This PR allows for disabling tests by setting BUILD_TESTING (built-in) option to OFF.
Tests are enabled by default.

### CODE REVIEW

**Comment by giraldeau** [comment]
Good catch. We should add the option with other build options currently available, such as: 

```
option(BUILD_TESTING "Build the tests" ON)
```

What do you think?

**Comment by giraldeau** [comment]
Well, as you said, it's built-in, so no need to explicitely define it. Please disregard my previous comment.

**Comment by giraldeau** [comment]
LGTM

**Comment by mliszcz** [comment]
Thanks for checking the PR. Yes, BUILD_TESTING is built-in and even provides a textual descriptions for tools like IDEs.
```
$ cmake3 .. -LH | grep BUILD_TESTING -B 1
// Build the testing tree.
BUILD_TESTING:BOOL=ON
```

**Comment by beltoforion** [comment]
@giraldeau Thanks for the review. I'll merge

**Pull request merged**
