### PR TITLE
Add cmake build system

### PR DESCRIPTION
**Pull request by giraldeau**
Provide the option to use CMake as a build system.

Signed-off-by: Francis Giraldeau <francis.giraldeau@canada.ca>

### CODE REVIEW

**Comment by giraldeau** [comment]
You can test this feature using these commands (on Ubuntu):

```
apt install cmake
mkdir build && cd build
cmake <pathToMuParser>
make
sudo make install
```
Hopefully, this should streamline the build system. Thanks!

**Comment by giraldeau** [comment]
I just saw that there was a previous pull-request with cmake build system: 

  https://github.com/beltoforion/muparser/pull/13/files

Is there a reason why this was not merged? At first sight, it looks good.

**Comment by beltoforion** [comment]
Lack of time to verify it and i believe it made changed to files that were automatically created.

I'd be in favor of dropping bakefile completely because it's not worth the hassle any more. personally I have never used CMake before and do not have the time to get into it. 

What i would need right now is someone willing to invest the time to provide me with a working implementation that can produce static libraries as well as dynamic libraries based on cmake. I'd like to avoid a situation were i am stuck with an untested cmake based build system that i have to maintain without really having worked with CMake before.

If you are willing to invest the time i can either pull your changes or give you the authority to add them yourself. 

The chances of me doing this on my own are slim to none. So any help would be appreciated.

**Comment by giraldeau** [comment]
I do CMake everyday, so that would be a pleasure to help with that. Currently, we can switch between shared and static libraries using the proposed CMakeLists.txt with this global option at configure time:
```
# build static libmuparser.a
cmake -DBUILD_SHARED_LIBS=OFF ../

# build static libmuparser.so
cmake -DBUILD_SHARED_LIBS=ON ../
```
Cheers!

**Comment by giraldeau** [comment]
As for the PR or direct access, I will let that decision to your discretion, either one is fine. Thanks!

**Comment by mepholic** [comment]
+1 this would make packaging much easier!

**Comment by giraldeau** [comment]
@mepholic it makes me thing: the pkg-config file is not installed at the moment. I will make sure there is no such regression for package users.

**Comment by giraldeau** [comment]
Done. The installation now produce the same files as the legacy build system. Here is an example with 
`-DCMAKE_INSTALL_PREFIX=/tmp/usr`:

```
/tmp/usr/
├── include
│   ├── muParserBase.h
│   ├── muParserBytecode.h
│   ├── muParserCallback.h
│   ├── muParserDef.h
│   ├── muParserDLL.h
│   ├── muParserError.h
│   ├── muParserFixes.h
│   ├── muParser.h
│   ├── muParserInt.h
│   ├── muParserStack.h
│   ├── muParserTemplateMagic.h
│   ├── muParserTest.h
│   ├── muParserToken.h
│   └── muParserTokenReader.h
└── lib
    ├── libmuparser.so -> libmuparser.so.2
    ├── libmuparser.so.2 -> libmuparser.so.2.2.4
    ├── libmuparser.so.2.2.4
    └── pkgconfig
        └── muparser.pc
```

And the content of `muparser.pc`:

```
prefix=/tmp/usr
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: muparser
Description: Mathematical expressions parser library
Version: 2.2.4
Requires:
Libs: -L${libdir} -lmuparser
Cflags: -I${includedir}
```

**Comment by beltoforion** [comment]
Thanks alot for doing this. I appreciate it very much. I added you as a collaborator to the project. That should give you direct access to the repository.

**Comment by mepholic** [comment]
Just wanted to point out that this is tested and working on Alpine Linux's build system. Thank you very much for this PR! If there's any chance this could be rolled into a release any time soon, that would be awesome.

**Comment by beltoforion** [comment]
Thanks for the feedback. Ideally i'd like to drop bakefile altogether before creating a new release because getting it to work on my current machine is probably quite painful.

**Pull request merged**
